AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda to send SMS

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 30
    MemorySize: 128

Resources:
  AudioLogFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        AUDIOGET:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /portfolio/audiolog
            Method: GET
        AUDIOOPTIONS:
          Type: Api
          Properties:
            Path : /portfolio/audiolog
            Method : OPTIONS
        RESUMEGET:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /portfolio/resume
            Method: GET
        RESUMEOPTIONS:
          Type: Api
          Properties:
            Path : /portfolio/resume
            Method : OPTIONS
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject 
              Resource: arn:aws:s3:::thatshashankguy-storage-bucket/*  
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          STORAGE_BUCKET: thatshashankguy-storage-bucket
          AUDIO_ADDRESS : podcast
          RESUME_KEY : documents/Resume.pdf
          MY_AWS_REGION : ap-south-1  
  AdminFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: go1.x
    Properties:
      CodeUri: src/
      Handler: bootstrap
      Runtime: provided.al2
      Architectures:
        - x86_64
      Events:
        GETAUDIOINFO:
          Type: Api 
          Properties:
            Path: /admin/audio
            Method: GET
        OPTIONSAUDIOINFO:
          Type: Api
          Properties:
            Path : /admin/audio
            Method : OPTIONS
        POSTUPLOADURL:
          Type: Api 
          Properties:
            Path: /admin/upload-url
            Method: POST
        OPTIONSUPLOADURL:
          Type: Api
          Properties:
            Path : /admin/upload-url
            Method : OPTIONS
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
                - s3:PutObject
              Resource: arn:aws:s3:::thatshashankguy-storage-bucket/*  
            - Effect: Allow
              Action:
                - s3:ListBucket
              Resource: arn:aws:s3:::thatshashankguy-storage-bucket/
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          STORAGE_BUCKET: thatshashankguy-storage-bucket
          AUDIO_ADDRESS : podcast
          MY_AWS_REGION : ap-south-1  
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PORTFOLIOAPI:
    Description: "API Gateway endpoint URL for Portfolio Backend"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/portfolio/"
  PortfolioFunction:
    Description: "Portfolio Lambda Function ARN"
    Value: !GetAtt AudioLogFunction.Arn
  PortfolioFunctionIamRole:
    Description: "Implicit IAM Role created for Portfolio function"
    Value: !GetAtt AudioLogFunctionRole.Arn
  AdminFunction:
    Description: "Admin Panel function"
    Value: !GetAtt AdminFunction.Arn
  AdminFunctionIamRole:
    Description: "Implicit IAM Role created for Admin Panel function"
    Value: !GetAtt AdminFunctionRole.Arn
  


  
