name: Deploy Lambda to AWS

on:
  workflow_dispatch: # This triggers the workflow manually

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1
      
      - name: Change directory to functions folder
        run: cd functions

      - name: Build and package AWS SAM application
        run: |
          sam build --template template.yml
          sam package --output-template-file packaged.yaml

      - name: Deploy AWS SAM application
        run: |
          sam deploy \
            --template-file packaged.yaml \
            --stack-name YourLambdaStackName \
            --capabilities CAPABILITY_IAM

      - name: Clean up
        run: |
          rm -f packaged.yaml
